#!/bin/bash

echo "========================================"
echo "📖 多跳组合机制详解"
echo "========================================"
echo ""

echo "提供了2个文档："
echo ""
echo "1. 📖多跳组合机制详解.md  ← 完整详细版"
echo "2. 🎯多跳组合_简明版.md   ← 快速理解版"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 目录"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Statements（技术陈述）的作用"
echo "   ├─ 定义：一句话概括QA的技术关系"
echo "   ├─ 数据结构：memory.statements = [s1, s2, ...]"
echo "   ├─ 作用1：生成多跳问题的上下文"
echo "   ├─ 作用2：检查信息覆盖（避免重复）"
echo "   └─ 作用3：展示给用户/LLM"
echo ""
echo "2️⃣  桥联（Bridge）检查的逻辑"
echo "   ├─ 定义：验证两个QA能否合理组合"
echo "   ├─ 步骤1：生成link_qa（桥联陈述）"
echo "   ├─ 步骤2：check_bridge_validity（评估相关性）"
echo "   ├─ 步骤3：判断阈值（score >= 2 接受）"
echo "   └─ 放宽阈值：从6降到2（通过率70%）"
echo ""
echo "3️⃣  组合流程"
echo "   ├─ 选择邻居QA"
echo "   ├─ 桥联检查（相关性 >= 2）"
echo "   ├─ 信息去重（不重复）"
echo "   ├─ 多跳组合（生成新问题）"
echo "   ├─ 筛选评估（6个标准）"
echo "   ├─ 答案重生成（基于子QA）"
echo "   └─ 直接接受（移除测试）"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 快速查看"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "【1. Statements示例】"
echo ""
echo "  memory.relevant = [QA-1647, QA-6460]"
echo ""
echo "  memory.statements = ["
echo "    \"PFM与KPFM通过机械形变和电势测量互补揭示...\",  # QA-1647"
echo "    \"有机硅通过氢钝化抑制界面缺陷...\"            # QA-6460"
echo "  ]"
echo ""
echo "  作用：生成多跳问题时提供简洁的技术陈述"
echo ""

echo "【2. 桥联检查示例】"
echo ""
echo "  QA1: PFM与KPFM在铁电材料表征"
echo "  QA2: 有机硅与SiO₂对TFT器件的影响"
echo ""
echo "  桥联陈述: 都涉及界面工程和材料特性"
echo ""
echo "  LLM评估: {"
echo "    \"relevance_score\": 6,  # 8-10: 高相关, 5-7: 中等, 2-4: 低, 0-1: 无"
echo "    \"reason\": \"两个QA都涉及界面特性，有技术关联\""
echo "  }"
echo ""
echo "  判断: score (6) >= 2 → ✅ 接受"
echo ""

echo "【3. 组合流程示例】"
echo ""
echo "  第1轮: Action=none"
echo "    → memory.relevant = [QA-1647]"
echo "    → num_hops = 1"
echo ""
echo "  第2轮: Action=SELECT"
echo "    → 选择邻居: 6460"
echo "    → 桥联检查: score=6 ✓"
echo "    → 多跳组合: 生成2跳问题"
echo "    → 筛选通过 ✓"
echo "    → 直接接受 ✓"
echo "    → memory.relevant = [QA-1647, QA-6460]"
echo "    → num_hops = 2"
echo ""
echo "  第3轮: Action=SELECT"
echo "    → num_hops (2) >= target_hops (2)"
echo "    → 跳过"
echo ""
echo "  第4轮: Action=EXIT"
echo "    → 退出"
echo ""
echo "  保存: {"
echo "    \"source_qa_ids\": [1647, 6460],"
echo "    \"statements\": [s1, s2],"
echo "    \"num_hops\": 2,"
echo "    \"final_qa_count\": 2"
echo "  }"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 查看详细文档"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 完整详细版（包含代码、例子、Prompt）"
echo "cat 📖多跳组合机制详解.md"
echo ""
echo "# 快速理解版（简明扼要）"
echo "cat 🎯多跳组合_简明版.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 核心总结"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Statements = 每个QA的一句话技术概括"
echo "   └─ 用于：生成多跳问题、检查重复、展示关系"
echo ""
echo "2. 桥联检查 = 确保两个QA有逻辑联系"
echo "   └─ 阈值：score >= 2 接受（放宽后通过率70%）"
echo ""
echo "3. 组合流程 = 选邻居 → 桥联 → 去重 → 组合 → 筛选 → 接受"
echo "   └─ 关键：移除测试环节，提升多跳成功率"
echo ""
